### ISSUE TITLE
Add github link to package.json

### ISSUE THREAD

**Issue by AndrewRayCode** [bvaughn/progress-estimator#1]
so source code shows up on https://www.npmjs.com/package/progress-estimator

**Comment by bvaughn** [comment]
I already added the link with 0.1.1

Does this info not show up for you?
<img width="329" alt="screen shot 2018-11-24 at 2 16 26 pm" src="https://user-images.githubusercontent.com/29597/48973413-8c048d00-eff3-11e8-9f9b-6606c8d07d47.png">

**Comment by bvaughn** [comment]
Pretty sure this was resolved pretty soon after I published 0.1.0 and realized this info was missing. I suspect you just didn't see it because of a propagation delay.
