### ISSUE TITLE
Types seem pretty broken

### ISSUE THREAD

**Issue by hipstersmoothie** [bvaughn/progress-estimator#15]
The types seem to be wrong

![Screen Shot 2019-07-02 at 2 50 25 PM](https://user-images.githubusercontent.com/1192452/60549106-c0060600-9cd8-11e9-8c76-70745938f961.png)

The types export a bunch of things the library doesn't seem to export. Such as the `configure` function.

Here are the fixed types:

```ts
import { Chalk } from 'chalk';

export interface Spinner {
  interval: number;
  frames: string[];
}

export interface ChalkTheme extends Chalk {
  asciiCompleted: Chalk;
  asciiInProgress: Chalk;
  estimate: Chalk;
  estimateExceeded: Chalk;
  label: Chalk;
  percentage: Chalk;
  progressBackground: Chalk;
  progressForeground: Chalk;
}

export interface Configuration {
  spinner?: Spinner;
  storagePath?: string;
  theme?: ChalkTheme;
}

export type ProgressEstimator = <T>(
  promise: Promise<T>,
  label: string,
  estimatedDuration?: number
) => Promise<T>;

declare const configure: (options: Configuration) => ProgressEstimator;

export default configure;
```

**Comment by bvaughn** [comment]
I'm not a TypeScript user. I didn't add these types (#4) and I don't care to maintain them. If you'd like to submit a PR to change them, I can merge it at some point.
