### ISSUE TITLE
Suggestion: return configurator, not mutate semi-globals

### ISSUE THREAD

**Issue by AndrewRayCode** [bvaughn/progress-estimator#2]
Your `configure()` code mutates some semi-global variables. It would be nicer for the end consumer to have the creation function return a new object bound to its own options, to potentially use more than one

**Comment by bvaughn** [comment]
I actually intentionally chose the global mutation option because it seemed a bit more convenient. Didn't seem like people would want multiple, independent instances of this utility. Can you describe what kind of use case you're thinking about that would actually use this?

**Comment by def14nt** [comment]
@bvaughn Sorry for posting it here, but what is that shell you're using in the README? I could use something like that.

**Comment by bvaughn** [comment]
It's [Oh My Zsh](https://ohmyz.sh) with the [Dracula theme](https://draculatheme.com).

**Comment by sompylasar** [comment]
Bit yes, it's unlikely that the parallel tasks would use different `storagePath` as their states are tracked in fikes under this path (it's a directory). They could potentially use a different `theme` to color different tasks differently. Using a different `spinner` shape is unlikely.

**Comment by bvaughn** [comment]
Implemented in 8775409. Will be released shortly with 0.2.0
