### ISSUE TITLE
0.3.0 Release?

### ISSUE THREAD

**Issue by michaeljaltamirano** [bvaughn/progress-estimator#22]
Hi Brian,

I added `progress-estimator` to a little script I wrote around the same time you had initially shared it. I've (somewhat regretfully) been adding TypeScript support to my own script, and it looks like pulling `progress-estimator` from `npm` results in the `0.2.2` version that doesn't have some of the more recent commits to master.

I'm putting at the repo directly for now, but figured I'd open the issue in case it was of interest to you (or others). Thanks for the neat library!

**Comment by bvaughn** [comment]
To my knowledge, there's nothing in 0.3 other than updated TypeScript definitions. The rest of the changes in master are README files or unobservable code tweaks.

**Comment by bvaughn** [comment]
Bu sure, v0.3 was just published
