### ISSUE TITLE
Suggestion: reduce dependencies by replacing chalk with colorette

### ISSUE THREAD

**Issue by dmitry-vakhnenko** [bvaughn/progress-estimator#3]
Hello, @jorgebucaran created npm package that better than chalk. Its, faster, zero-dependency, blazing fast ;-D alternative.

https://github.com/jorgebucaran/colorette

Can this project use it instead of chalk?

**Comment by bvaughn** [comment]
I'm a pretty big fan of the `chalk` package, and in this case I specifically make use of it's "theming" support. I haven't really seen `colorette` before but it doesn't look like it supports theming, and `chalk` seems plenty fast for the purposes of this little library 😄

Thanks for the suggestion though! I'll try to play with `colorette` at some point soon and check it out.
