### ISSUE TITLE
setInterval timer isn't cleared when the promise rejects (in the catch)

### ISSUE THREAD

**Issue by sompylasar** [bvaughn/progress-estimator#5]
https://github.com/bvaughn/progress-estimator/blob/c5bdf72/src/index.js#L70-L72

https://github.com/bvaughn/progress-estimator/blob/c5bdf72/src/index.js#L88-L92

**Comment by bvaughn** [comment]
That's true. I guess in my case, a rejected project always results in an `process.exit(1)` but you're right to mention that I should make sure it's cleared in case that's not true for others. I'll move it too a `finally` block.

**Comment by bvaughn** [comment]
Fixed with 1d2b088. Will release in the next patch update, shortly.
