### ISSUE TITLE
Suggestion: a way to inject a function instead of logUpdate

### ISSUE THREAD

**Issue by sompylasar** [bvaughn/progress-estimator#6]
To integrate with [listr](https://github.com/SamVerschueren/listr) where you can have many long tasks running in parallel and which uses its own renderer with `log-update` under the hood and provides a `task.output` abstraction to update the display, it would be beneficial to split this library's output string generation from printing/updating the terminal.

This can be simply done by providing a way to the caller of `logProgress` to replace `logUpdate` with a custom object provided via the `logProgress` arguments (potentially the fourth or the third should be the `options` object).

**Comment by bvaughn** [comment]
Implemented in 8775409. Will be released shortly with 0.2.0
