### ISSUE TITLE
Suggestion: Add an explicit value to hash instead of relying on label

### ISSUE THREAD

**Issue by jumoel** [bvaughn/progress-estimator#8]
I'm using `progress-estimator` with an ESlint wrapper. The expected runtime is thus dependent on the number of files and can fluctuate a lot (`eslint-wrapper singlefile.js` vs. `eslint-wrapper some/dir`).

It'd be nice if the label could be consistent, while still having somewhat usable time estimates.

**Comment by bvaughn** [comment]
Fair enough. I was on the fence about this, but wasn't convinced it was worth the API complexity increase. I think a way to provide this as an optional value would be nice.

**Comment by bvaughn** [comment]
Maybe something like:
```js
await logProgress(
  somePromise,       // required
  "This is a label", // required
  {                  // optional config object with optional keys
    estimatedDuration: Number
    id: Number
  }
);
```

**Comment by bvaughn** [comment]
Implemented in 8775409. Will be released shortly with 0.2.0

**Comment by jumoel** [comment]
Very nice - thank you! 😄

**Comment by bvaughn** [comment]
You're welcome!
